"""empty message

Revision ID: 8050c7ad18e7
Revises: 02781675c682
Create Date: 2020-04-30 16:50:03.409009

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8050c7ad18e7'
down_revision = '02781675c682'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mositure_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('mositure', sa.Integer(), nullable=True),
    sa.Column('density', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_mositure_data_time'), 'mositure_data', ['time'], unique=False)
    op.drop_index('ix_message_data_created_on', table_name='message_data')
    op.drop_table('message_data')
    op.drop_index('ix_question_created_on', table_name='question')
    op.drop_table('question')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('question',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('text', sa.VARCHAR(length=255), nullable=True),
    sa.Column('prediction', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_question_created_on', 'question', ['created_on'], unique=False)
    op.create_table('message_data',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('message', sa.VARCHAR(), nullable=True),
    sa.Column('prediction', sa.INTEGER(), nullable=True),
    sa.Column('created_on', sa.DATETIME(), nullable=True),
    sa.Column('density', sa.INTEGER(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_message_data_created_on', 'message_data', ['created_on'], unique=False)
    op.drop_index(op.f('ix_mositure_data_time'), table_name='mositure_data')
    op.drop_table('mositure_data')
    # ### end Alembic commands ###
