"""empty message

Revision ID: a620b9628add
Revises: 8050c7ad18e7
Create Date: 2020-05-11 11:05:25.070811

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a620b9628add'
down_revision = '8050c7ad18e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ph_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pH', sa.Integer(), nullable=True),
    sa.Column('density', sa.String(length=255), nullable=True),
    sa.Column('time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ph_data_time'), 'ph_data', ['time'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_ph_data_time'), table_name='ph_data')
    op.drop_table('ph_data')
    # ### end Alembic commands ###
